### ISSUE TITLE
nmud requires missing file(s)

### ISSUE THREAD

**Issue by marado** [ProjectMoon/nmud#2]
Either there's no use for the `nmud` file anymore, or you forgot to git add a file or directory, because it does `require("./mud");` but no such file or directory exists.

**Comment by ProjectMoon** [comment]
Truthfully it might be because this was a prototype repository, and maybe I forgot to include the file in it. I have a feeling requiring mud.js might have been a script for setting up the game world. It has been a long time so I don't really know anymore.
